### ISSUE TITLE
Zervo.py

### ISSUE THREAD

**Issue by m1kuwu** [zeviel/zervo.py#1]
main.py file
`import zervo
zervo = zervo.Zervo()
zervo.login(email="email@gmial.com", password="supersecretpassword")`

`Traceback (most recent call last):
  File "/home/drax/python/zervo/zervo.py/src/main.py", line 3, in <module>
    zervo.login(email="email@gmial.com", password="supersecretpassword")
  File "/home/drax/python/zervo/zervo.py/src/zervo.py", line 66, in login
    if "token" in response["data"]["pinponToken"]:
KeyError: 'data'
`

**Comment by vraestoren** [comment]
@gmail.com not @gmial.com

ср, 15 февр. 2023 г., 19:43 DarindaDraX ***@***.***>:

**Comment by m1kuwu** [comment]
Is there any documentation about how to use it
how to get ids

**Comment by vraestoren** [comment]
what ids do you want to get?

> Is there any documentation about how to use it how to get ids

**Comment by m1kuwu** [comment]
> what ids do you want to get?
> 
> > Is there any documentation about how to use it how to get ids

done I use http toolkit to get ids
ids like group id , user id etc
if there is any better way to get this pls tell me

**Comment by m1kuwu** [comment]
`import zervo
zervo = zervo.Zervo()
zervo.login(email="", password="")
x=zervo.invite_to_channel(channel_id=1626130590887706625,user_id=1570612438489030657)
print(x)`


`{'code': 415, 'success': False, 'msg': "Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported"}`

**Comment by vraestoren** [comment]
> > what ids do you want to get?
> > > Is there any documentation about how to use it how to get ids
> 
> done I use http toolkit to get ids ids like group id , user id etc if there is any better way to get this pls tell me

```python
recommended_users = zervo.get_recommended_users(current=1, size=10)
print(recommended_users)
```
to get recommended users, ids will be in response.
also you can use
```
get_recommended_channels
get_recent_posts
```
and other functions to get ids
